version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ttv-service
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
